### ISSUE TITLE
Genomes, number of sgRNAs

### ISSUE THREAD

**Issue by amv33576** [akikuno/DAJIN#45]
Hello, 
Some questions about implementation:
1. Can you use this software with other genomes? 
2. Is it possible to input more than one sgRNA? We used the https://ice.synthego.com/#/ with our sanger sequences.

I have an amplicon nanopore sequencing from insect genomes after mosaic CRISPR knockouts. the genomes are not in UCSC. I will really like to try your software on my data. 

Best,

Anyi

**Comment by akikuno** [comment]
Hello, Anyi,

Sorry for the late reply and Thank you for your message.

1. Currently, DAJIN can analyze only animals with UCSC references. We are planning to update and include organisms without UCSC references. 

2. Multiple sgRNAs can be applicable. Since the current DAJIN requires two alleles (wt and target), please create an arbitral target allele as shown below in the case of 1 cut deletion.

```
>wt
ACGTACGT
>target
ACGTAACGT
```

Sincerely,

Kuno
